### ISSUE TITLE
[1.0.0.0] Lock dupe bug when removing from chest

### ISSUE THREAD

**Issue by starg09** [TehStoneMan/BetterStorageToo#1]
Tested on Forge 2281, v1.0.0.0 of the mod. Placing a lock on a chest doesn't remove it from your inventory. So, when you remove it from the chest when sneak-rightclicking with the key, you get a duplicate lock.

**Comment by TehStoneMan** [comment]
Is this in creative or survival?

**Comment by starg09** [comment]
Both.
