### ISSUE TITLE
Multiblock Storage Crate + Simple Storage Network Crash + Refined Storage + Issues

### ISSUE THREAD

**Issue by Tanto17** [TehStoneMan/BetterStorageToo#11]
Hello! 
Thank you for bringing this mod to 1.12.2!
I would like to get this mod into my current modpack but am having issues with it and Simple Storage network (https://minecraft.curseforge.com/projects/simple-storage-network). 

Fist things first, the Storage Link cables do not connect to the reinforced chest, nor any version of the storage lockers.  Storage link cables do connect to the storage crate.

However this brings me to the second issue. If the Simple Storage Network is connected to a multi block crate, I get this crash when attempting to access the Network.
 https://pastebin.com/wKXtdZND

Forge:14.23.4.2760.
Simple Storage Network: 1.4.0
Better Storage Too:3.0.0.0

**Comment by Tanto17** [comment]
Out of my own curiosity I tested it with Refined Storage.  Same issues occurred.  External Storage did not properly interact with lockers and reinforced chests. And I received this crash when I put an External Storage Bus on a multiblock crate.  https://pastebin.com/5yqsdgxz

Forge:14.23.4.2760.
Refined Storage: 1.6.5
Better Storage Too:3.0.0.0

**Comment by TehStoneMan** [comment]
Should be fixed now.

**Comment by Tanto17** [comment]
Thank you!
