### ISSUE TITLE
Linked when storage crate is moved by CarryOn

### ISSUE THREAD

**Issue by maksim789456** [TehStoneMan/BetterStorageToo#12]
Hey
I found a bug. When a block gets from the Storage crate structure with the help of CarryOn, it is linked with a large structure.
![2018-09-30_14 31 15](https://user-images.githubusercontent.com/8225008/46256576-9b68cd80-c4bd-11e8-9ef7-e1ddb23c5ae1.png)
![2018-09-30_14 31 20](https://user-images.githubusercontent.com/8225008/46256577-9b68cd80-c4bd-11e8-8bc9-14f145ffba71.png)
![2018-09-30_14 31 23](https://user-images.githubusercontent.com/8225008/46256578-9b68cd80-c4bd-11e8-966d-6e93373ab170.png)

Crash when interacting with related unit
https://pastebin.com/5cNKW8QQ

**Comment by TehStoneMan** [comment]
The crash has been fixed, but crates should not be moved that way. It would be best if they were blacklisted.

**Comment by Tschipp** [comment]
While I was investigating the compat issue that our mods have, I discovered this: Items in crates randomly switch slots... is this inteded behavior?
https://i.gyazo.com/9a7802450fe71355fa26a3274cd7d3e5.gif

Edit: in any case, I'll add betterstoragetoo to the default blacklist.

**Comment by TehStoneMan** [comment]
Yes. Crates have a random interface. They can hold more items that can appear in the gui, and the gui only shows a random subset of the contents.

**Comment by Tschipp** [comment]
Ah, I see
