### ISSUE TITLE
[1.12.2] CarryOn support (And a crash)

### ISSUE THREAD

**Issue by Tokeli** [TehStoneMan/BetterStorageToo#13]
Currently, when picking up any of the storage blocks using CarryOn, double-chests and double-lockers do not register that they've been disconnected, and one chest retains the model while the other is invisible.

There's also now a crash when trying to interact with chests or lockers that have been separated like that:
https://paste.dimdev.org/ekebajujic.mccrash

**Comment by TehStoneMan** [comment]
Unfortunately, chests and lockers are not designed to be moved in this fashion, and changing their behaviour would require major code rewrites. For now the best solution is to blacklist them from CarryOn.
