### ISSUE TITLE
[1.0.0.0] Some things related to lockers (behaviour, positioning, and a rendering bug)

### ISSUE THREAD

**Issue by starg09** [TehStoneMan/BetterStorageToo#2]
Again, tested on:

* BST 1.0.0.0
* Forge 2281

---

1. [You cannot place a locker with the handle facing the other way, like in previous versions.](https://gfycat.com/InsecureScholarlyCob) Wasn't sure if this was intended or not, so I thought about reporting it just in case 😄 

2. [Sides of the lockers don't react as solid blocks, like they used to.](https://gfycat.com/ImmediateGrizzledGuillemot) In the past, the door would also be the only way to access the inventory, but right clicking any of the other sides worked like if the block were a regular solid block (for example, a wooden plank). This allowed one to make a quick area of lockers in no time, instead of having to sneak to place them like with vanilla chests. A mod that does something similar is Storage Drawers, with its... Well, drawers :P 

3. [A small rendering bug when looking to a locker from certain angles.](https://gfycat.com/FaintElatedBeauceron) Only seems to affect 2-block high lockers, single look ok.

**Comment by TehStoneMan** [comment]
1. Mainly just not implemented. Model support in 1.10 is different from the when the original was written, so some things don't work the same as it used to.

2. Wasn't aware the old version did that. Something to keep in mind for future updates.

3. OK, I can see what's happening there. The door rendering is attached to the lower locker, so it disappears when it goes out of view.

These aren't games breaking issues, so for now I mainly want to focus on a 1.11 version, but I do plan to backport fixes and missing features as I get to them.

**Comment by starg09** [comment]
Oh, that sounds great! And I actually liked forward to a 1.11 build for our
pack, so won't really depend on the backport :)
