### ISSUE TITLE
MIT license violation

### ISSUE THREAD

**Issue by asiekierka** [TehStoneMan/BetterStorageToo#4]
You have changed the copyright owner on the LICENSE file in this repository.

Notice that the license states:

    The above copyright notice and this permission notice shall be included in all
    copies or substantial portions of the Software.

If you fork an MIT-licensed project, you *may not* change the existing copyright notice - you may only append your own, to cover your additions to said code, but you cannot just remove the existing copyright owner from the LICENSE file.

**Comment by copygirl** [comment]
I have essentially given permission several times that the mod may be considered public domain and as such I do not care about forks changing the license. The MIT license was only added after you, @asiekierka, nagged about BetterStorage not having a license and thus not officially being FOSS, after all `:p`

**Comment by asiekierka** [comment]
@copygirl Might be worth keeping your copyright notice on the code, though. Just as a legal equivalent of a token of credit.

**Comment by copygirl** [comment]
That's completely optional in my opinion so it'd be up to @TehStoneMan. Though I dislike that someone called "CopyGirl" is being credited for creating the mod. Who is that?

**Comment by TehStoneMan** [comment]
I hope these changes https://github.com/TehStoneMan/BetterStorageToo/commit/b1c3278c9c9d52547e9d47aad0bcc08b31aef53a are satisfactory.
